### ISSUE TITLE
grid 0.3.92 running grid clusters  results in TypeError: composite_channel_credentials() got an unexpected keyword argument 'options'

### ISSUE THREAD

**Issue by robert-s-lee** [gridai/gridai#129]
## 🐛 Bug

running `grid clusters` on python 3.9.7 and 3.8 result in `TypeError: composite_channel_credentials() got an unexpected keyword argument 'options'`

### Expected behavior

`grid clusters` work on python 3.9.7 and 3.8

### Current behavior

```bash
conda create --yes --name py397 python=3.9.7
conda activate py397
grid clusters
```

```log
Traceback (most recent call last):
  File "/opt/miniconda3/envs/py397/bin/grid", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/py397/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/envs/py397/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/envs/py397/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/envs/py397/lib/python3.9/site-packages/click/core.py", line 1646, in invoke
    super().invoke(ctx)
  File "/opt/miniconda3/envs/py397/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/envs/py397/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/miniconda3/envs/py397/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/miniconda3/envs/py397/lib/python3.9/site-packages/grid/cli/cli/grid_clusters.py", line 102, in clusters
    clusters: [Cluster] = asyncio.run(list_clusters())
  File "/opt/miniconda3/envs/py397/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/miniconda3/envs/py397/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/miniconda3/envs/py397/lib/python3.9/site-packages/grid/cli/cli/grid_clusters.py", line 87, in list_clusters
    async with Grid.grpc_channel() as conn:
  File "/opt/miniconda3/envs/py397/lib/python3.9/contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "/opt/miniconda3/envs/py397/lib/python3.9/site-packages/grid/cli/client.py", line 346, in grpc_channel
    grpc.composite_channel_credentials(
TypeError: composite_channel_credentials() got an unexpected keyword argument 'options'
```

### To Reproduce

see above

### Environment

 - OS (e.g., Windows): osx
 - Browser (e.g., Chrome, Safari): N/A
 - CLI version: Grid CLI (v0.3.92)

### Additional context

`grid status` works as expected.

workarounds:
1) preferred

`pip install lightning-grid==0.3.91` works 

2) if Grid 0.3.92 is required
comment out the options line in client.py and it started working:
```
grpc.composite_channel_credentials(
                channel_creds,
                call_credentials,
                # options=[('grpc.max_receive_message_length', GRID_GRPC_MAX_MESSAGE_LENGTH)]
            )
        ) as channel:
            yield channel
```

**Comment by sunitaprakash** [comment]
Hello,

Thank you for reaching out to us.  This is a known issue. We are working on a fix and will to prod soon.
In the mean please use the pip install lightning-grid==0.3.91 as workaround.

**Comment by sunitaprakash** [comment]
Hi! @robert-s-lee 
The fix for this issue is now in production. Please let us know if you have any further issues here and appreciate your patience while we resolved the issue.
Please update the CLI : pip install lightning-grid --upgrade
